on:
  push:
    tags:
      - '*'
jobs:
  copy-folders:
    strategy:
      matrix:
        framework:
          - vue
          - react
          - javascript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set variables
        id: vars
        run: echo "basename=$(basename ${{github.ref}})" >> $GITHUB_OUTPUT
      - name: Create artifacts directory
        run: mkdir -p ${{github.workspace}}/artifacts
      - name: Copy and zip ${{ matrix.framework }}
        run: |
          cd ${{github.workspace}}/artifacts
          cp -R ${{github.workspace}}/${{ matrix.framework }} ${{ matrix.framework }}-${{ steps.vars.outputs.basename }}
          zip -9 -r ${{ matrix.framework }}-${{ steps.vars.outputs.basename }}.zip ${{ matrix.framework }}-${{ steps.vars.outputs.basename }}
      - name: Upload ${{ matrix.framework }} artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{github.workspace}}/artifacts/${{ matrix.framework }}-${{ steps.vars.outputs.basename }}.zip
          asset_name: ${{ matrix.framework }}-${{ steps.vars.outputs.basename }}.zip
          tag: ${{ github.ref }}
          overwrite: true
