on:
  push:
    tags:
      - '*'
jobs:
  copy-folders:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create artifacts directory
      run: mkdir -p ${{github.workspace}}/artifacts
    - name: Copy vue
      run: cp -R Vue ${{github.workspace}}/artifacts/vue-$(basename ${{github.ref}})
    - name: Copy react
      run: cp -R React ${{github.workspace}}/artifacts/react-$(basename ${{github.ref}})
    - name: Copy javascript
      run: cp -R Javascript ${{github.workspace}}/artifacts/javascript-$(basename ${{github.ref}})
    - name: Upload vue artifact
      uses: actions/upload-artifact@v3
      with:
        name: vue-$(basename ${{github.ref}})
        path: artifacts/vue-$(basename ${{github.ref}})
    - name: Upload react artifact
      uses: actions/upload-artifact@v3
      with:
        name: react-$(basename ${{github.ref}})
        path: artifacts/react-$(basename ${{github.ref}})
    - name: Upload javascript artifact
      uses: actions/upload-artifact@v3
      with:
        name: javascript-$(basename ${{github.ref}})
        path: artifacts/javascript-$(basename ${{github.ref}})
